[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  SECRETS_SCAN_OMIT_KEYS = "SUPABASE_URL,S3_BUCKET,CORS_ORIGIN"

[[plugins]]
  package = "@netlify/plugin-nextjs"
